// - UI
export const SWITCH_THEME = 'SWITCH_THEME';
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP';

// - Fetching Artists
export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTISTS_ERROR = 'FETCH_ARTISTS_ERROR';

// - Artist Manipulation
export const SEARCH_THROUGH_ARTISTS = 'SEARCH_THROUGH_ARTISTS';
export const SORT_ARTISTS_ALPHABETICAL = 'SORT_ARTISTS_ALPHABETICAL';
export const SORT_ARTISTS_REVERSE_ALPHABETICAL = 'SORT_ARTISTS_REVERSE_ALPHABETICAL';


